# Generated by Django 5.1.4 on 2024-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='media',
        ),
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
