# Generated by Django 5.1.4 on 2024-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_media_question_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
