# Generated by Django 5.1.4 on 2024-12-12 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_board_activate_board_end_time_board_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 시각'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='보드 활성화'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보드 생성자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='투표 종료시각'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, verbose_name='보드의 이름'),
        ),
        migrations.AlterField(
            model_name='board',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='투표 시작시각'),
        ),
    ]
