# Generated by Django 5.1.4 on 2024-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_board_created_at_alter_board_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='투표 종료 여부'),
        ),
    ]
